### ISSUE TITLE
Wrong property when attaching Error to ErrorDocument 

### ISSUE THREAD

**Issue by cincauhangus** [json-api-php/json-api#106]
When attaching Errors to an existing ErrorDocument, it doesn't appear in the json_encode output because it's placed in the wrong property (`$obj` vs `$error`)

https://github.com/json-api-php/json-api/blob/4eb1497ffe1dd685716a66f92ceb1561d7bc7045/src/Error.php#L28-L31

https://github.com/json-api-php/json-api/blob/4eb1497ffe1dd685716a66f92ceb1561d7bc7045/src/ErrorDocument.php#L13-L21

**Comment by cincauhangus** [comment]
Workaround:
```
foreach ($errors as $error) {
    $error_list[] = new Error(
        new Title($key),
        new Detail($error)
    );
}
new ErrorDocument(...$error_list);
```

**Comment by f3ath** [comment]
This is the intended behavior. The word "immutable" is there for a reason. https://github.com/json-api-php/json-api#json-api-spec-implemented-in-php-7-immutable
