### ISSUE TITLE
"Identifies" relation

### ISSUE THREAD

**Issue by f3ath** [json-api-php/json-api#16]
Native English speaker needed (@tobscure?)

> Compound documents require “full linkage”, meaning that every included resource MUST be **identified by** at least one resource identifier object in the same document. These resource identifier objects could either be primary data or represent resource linkage contained within primary or included resources.

Which is the best?

* `$a->identifies($b): bool`
* `$a->doesIdentify($b): bool`
* `$b->isIdentifiedBy($a): bool`
* `$a->isIdentityOf($b): bool`

**Comment by tobyzerner** [comment]
I like `$a->identifies($b): bool`

**Comment by f3ath** [comment]
So be it. Thanks
