### ISSUE TITLE
Implement Attribute Name Validation

### ISSUE THREAD

**Issue by f3ath** [json-api-php/json-api#3]
According to http://jsonapi.org/format/#document-member-names

**Comment by ghost** [comment]
Since this may be related, I was wondering why `type` is not a valid name for use within an `attributes` group? I get that it conflicts with use at a document or resource object level, but not in `attributes`.

**Comment by f3ath** [comment]
I am just following the documentation http://jsonapi.org/format/#document-resource-object-fields

"...a resource can not have an attribute and relationship with the same name, nor can it have an attribute or relationship named `type` or `id`."

**Comment by ghost** [comment]
Wow, I missed that. That's a little disappointing :(

**Comment by francislavoie** [comment]
Giving this one a shot. Will submit a PR in a bit.
