### ISSUE TITLE
Doesn't allow Document from no resources

### ISSUE THREAD

**Issue by ghost** [json-api-php/json-api#40]
The API spec allows a response to include no resources. Document here does not allow for this.

**Comment by f3ath** [comment]
Hi @johnrobertporter I think this test describes how it can be done: https://github.com/json-api-php/json-api/blob/master/test/Document/DocumentTest.php#L48

Please let me know if it helps.

**Comment by ghost** [comment]
Aha! Thanks for that, I missed that one.

Any way to create the empty collection Document?

**Comment by ghost** [comment]
Ok, missed that too, I found the test :)

https://github.com/json-api-php/json-api/blob/master/test/Document/DocumentTest.php#L69

**Comment by f3ath** [comment]
Thanks for trying it out. Please let memknow if it does what you exxpect.
