### ISSUE TITLE
Add name validation in meta

### ISSUE THREAD

**Issue by f3ath** [json-api-php/json-api#63]
Need to validate attribute names in `meta` objects. The validation should be deep, e.g. in this example an exception should be thrown:

```php
$m = Meta::fromArray([
  'valid_name' => [
    'valid_name_again' => [
      '#invalid_name_hidden_deeply' => 'omg'
    ]
  ]
]);
```
Add tests to [test/MemberNamesTest.php](../tree/master/test/MemberNamesTest.php).

**Comment by vtsykun** [comment]
Hi @f3ath 
please review https://github.com/json-api-php/json-api/pull/67
