### ISSUE TITLE
Add name validation in links 

### ISSUE THREAD

**Issue by f3ath** [json-api-php/json-api#66]
This is similar to #63. We need to validate link names in `setLink()` calls.

**Comment by martinjoiner** [comment]
Have the validation rules been defined? I could help with this.

**Comment by f3ath** [comment]
The spec is here http://jsonapi.org/format/#document-member-names
Also we have validation logic implemented in https://github.com/json-api-php/json-api/blob/master/src/Document/Resource/ResourceObject.php#L103

**Comment by f3ath** [comment]
We may consider a light refactoring to make the validation logic reusable across entities. The easiest way I can see is to move it to a trait.

**Comment by f3ath** [comment]
Fixed in #69
