### ISSUE TITLE
meta alongside data

### ISSUE THREAD

**Issue by vheubach** [json-api-php/json-api#85]
Hey there,

from the description it looks like you can either have errors, data or meta documents.

http://jsonapi.org/format/#document-meta specifies that meta can exist alongside data.

i am currently building compound documents, how would i go about "upgrading" that to include top-level meta information?

**Comment by f3ath** [comment]
This model allows to have both top level primary data and top level meta in one document. See how `document_meta` is added in [this example](https://github.com/json-api-php/json-api/blob/master/test/DataDocument/SingleResourceObjectTest.php#L65).

**Comment by vheubach** [comment]
thanks, i got it working!
