### ISSUE TITLE
Creating collections from array

### ISSUE THREAD

**Issue by techi602** [json-api-php/json-api#88]
I must be missing something very obvious yet I still can not understand how am I suppose to work with dynamic collections created from array. 
Imagine common task like retrieving orders from database and return several records as resource objects. (Number of orders is dynamic). 
How am I supposed to create resource collection? I can not simply pass array of Resource objects into constructor. I am aware of immutable objects, but still why I can not simply create immutable instance like ResourceArray and pass array of ResourceObjects ? Should I write my own ResourceArray class which will extend ResourceCollection and allow me to pass the array directly in constructor? 

even example here passes dynamic number of comments into constructor - not sure about this
https://github.com/json-api-php/json-api/blob/master/examples/compound_doc.php

@OndraM

**Comment by f3ath** [comment]
Hi @techi602. Thank you for your interest. This library makes extensive use of [variadic functions](http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list) to improve type safety. You can use [argument unpacking](https://wiki.php.net/rfc/argument_unpacking) to pass a dynamic number of arguments.
```php
$resources = getResources(); // array of ResourceObject
$collection = ResourceCollection(...$resources);
```

Let me know if this answers the question.

**Comment by f3ath** [comment]
>  but still why I can not simply create immutable instance like ResourceArray and pass array of ResourceObjects ? 

You can. But in this case you will either need to check that the elements of the array are `ResourceObjects` (which is cumbersome) or to blindly trust the user input. The variadic/unpacking approach lets php do the type checking. While it can still blow up in the runtime due to the dynamic nature of the language, the modern IDEs make sense of these type hints and reduce the chance of errors by checking types in the development time.

**Comment by techi602** [comment]
@f3ath thanks a lot! 👍  I was not aware of argument unpacking feature and "array type checking" I would suggest to add similar code to examples for other confused developers 😜

**Comment by f3ath** [comment]
@techi602 I would gladly accept a PR from you with such an example if you don't mind.
