### ISSUE TITLE
PHP 7.1 support

### ISSUE THREAD

**Issue by franzliedke** [json-api-php/json-api#89]
Do you *need* PHP 7.2 support in v2 of this library?
You seem to be using the new `object` typehint in some places, but I guess (hope) that's not life-critical. Is there anything else? Anything you wouldn't want to miss?

I am asking because we are considering using this library for Flarum (transitively through tobscure/json-api-server), and we want to keep supporting PHP 7.1 for a while.

**Comment by f3ath** [comment]
Sure we can downgrade to 7.1. Feel free to open a PR.

**Comment by f3ath** [comment]
Downgraded to 7.1 https://packagist.org/packages/json-api-php/json-api

**Comment by franzliedke** [comment]
Very cool, thanks for the quick reaction! And a happy new year to you! :fireworks:
