### ISSUE TITLE
Relationship without data property

### ISSUE THREAD

**Issue by OndraM** [json-api-php/json-api#92]
Hi,
I'd like to create resource with following relationship `my_relation`, which only contains `links` property, ie. there is no `data` property with resource linkage:

```json
{
    "data": {
        "type": "...",
        "id": "...",
        "relationships": {
            "my_relation": {
                "links": {
                    "related": "/foo"
                }
            }
        }
    }
}
```

This is allowed as per [JSON:API spec](https://jsonapi.org/format/#document-resource-object-relationships): 

>  A “relationship object” MUST contain at least one of the following:
>     - links: a links object 
>     - data: resource linkage
>     - meta: a meta object that contains non-standard meta-information about the relationship.

Is there any way how to accomplish this now, with version 2 of the library? It was possible with version 1:
```php
$resourceObject->setRelationship('my_relation', Relationship::fromRelatedLink('/foo'));
```

However now there seems to be only `ToNull`, `ToOne` and `ToMany` relation, neither of which accomplishes exactly this (eg. ToNull adds `data: null` to the relationship).

**Comment by f3ath** [comment]
Yep, you're right. The "at least one" clause makes `data` optional. Seems like introducing some sort of an `EmptyRelationship implements ResourceField` might solve this. What do you think?

**Comment by OndraM** [comment]
:+1: Yes, this is basically what I did as workaround. Though I'm not sure about  `EmptyRelationship` name - it suggest the relationship is empty, but it just does not contain the linkage identifier (ResourceIdentifier). However I can't think of better suggestion :)

**Comment by f3ath** [comment]
Feel free to submit a PR if you have it already.
