### ISSUE TITLE
Multi Attributes

### ISSUE THREAD

**Issue by mathieuhecker** [json-api-php/json-api#98]
How could we add multiple attributes dynamically ?

**Comment by f3ath** [comment]
Thank you for your interest. This library makes extensive use of [variadic functions](http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list) to improve type safety. You can use [argument unpacking](https://wiki.php.net/rfc/argument_unpacking) to pass a dynamic number of arguments.

**Comment by mathieuhecker** [comment]
Thank's
