### ISSUE TITLE
ResourceIdentifier meta

### ISSUE THREAD

**Issue by tobyzerner** [json-api-php/json-api#99]
The signature of `ResourceIdentifier` is:

```
public function __construct(string $type, string $id, Meta $meta = null)
```

`Meta` represents a single key-value pair. So how can you add multiple meta key-value pairs to a resource identifier object?

Relevant part of the spec: https://jsonapi.org/format/#document-resource-identifier-objects

**Comment by f3ath** [comment]
Should work in 2.1.1. Please confirm.

**Comment by tobyzerner** [comment]
🤯 speedy! Thanks.
